Repository saero-jinro/saerojinro-client, pull requests merged in 2025-04, with the labels that each got.

#174 design(lecture list, detail): 다크모드, 반응형 수정
  src/app/(route)/lecture-list/component/list.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
Labels: design

#176 design(etc): 접근선 개선, 디자인 수정
  src/app/(route)/lecture-list/component/list.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
  src/app/(route)/timetable/timetableComponent/timetablePage.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/_components/LectureReserveButton/LectureReserveButton.tsx
  src/app/_components/Wish/WishButton.tsx
Labels: design

#179 fix(delete/user): 회원 탈퇴 기능 수정
  src/app/(route)/(main)/mainComponent/FstSection.tsx
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/(main)/mainComponent/TrdSection.tsx
  src/app/(route)/login/admin/page.tsx
  src/app/(route)/mypage/component/dataComponents.tsx
  src/app/(route)/mypage/component/handleButton.tsx
  src/app/_components/Alarm/AlarmList.tsx
  src/app/_components/Alarm/AlarmWindow.tsx
  src/app/_hooks/nav/useAlarm.ts
  src/app/_styles/globals.css
  src/app/_styles/tiptap.css
  src/app/_utils/Auth/deleteUser.ts
  src/app/api/auth/user/route.ts
Labels: fix

#181 fix(loginComponent): 모바일 디자인 수정
  src/app/_components/Login/LoginComponent.tsx
  src/app/_components/Login/LoginModal.tsx
  src/app/assets/Header/kakaologo.svg
Labels: fix

#183 refactor(seo): 접근성 강화
  next.config.ts
  public/sitemap.xml
  src/app/(route)/(main)/mainComponent/FstSection.tsx
  src/app/(route)/admin/alarm/page.tsx
  src/app/(route)/layout.tsx
  src/app/(route)/lecture-list/component/list.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
  src/app/(route)/timetable/timetableComponent/timetablePage.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/Login/LoginComponenet.click.tsx
  src/app/_components/Login/LoginModal.tsx
  src/app/_components/Nav/HeaderNav.web.tsx
  src/app/_components/TextEditor/ColorPickerButton/ColorPickerbutton.tsx
Labels: refactor
