Repository saero-jinro/saerojinro-client, pull requests merged in 2025-03, with the labels that each got.

#3 FEAT(darkmode): 다크 모드 기능 추가
  .github/ISSUE_TEMPLATE/issue-템플릿.md
  .vscode/settings.json
  README.md
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  prettier.config.cjs
  src/app/(route)/(main)/page.tsx
  src/app/(route)/admin/page.tsx
  src/app/_components/ClickButton.tsx
  src/app/_components/Header/Header.test.tsx
  src/app/_components/Header/ThemeToggleButton/ThemeToggleButton.client.tsx
  src/app/_components/Header/ThemeToggleButton/ThemeToggleView.tsx
  src/app/_hooks/useTheme.tsx
  src/app/_store/test.ts
  src/app/_styles/fonts.css
  src/app/_styles/globals.css
  src/app/_types/Header/theme.ts
  src/app/_utils/Header/getTheme.server.ts
  src/app/api/test.ts
  src/app/api/test/route.ts
  src/app/dumyData/main/maindto.json
  src/app/dumyData/test.설명.ts
  src/app/layout.tsx
  tailwind.config.ts
Labels: feat

#8 FEAT(dummy): 라우팅 구조 설정 및 더미데이터 불러오기
  src/app/(route)/lecture-list/page.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/timetable/page.tsx
  src/app/api/test/route.ts
  src/app/dummyData/lecture-list/getLectureList.json
  src/app/dummyData/lecture/getLecture.json
  src/app/dummyData/lecture/getQuestion.json
  src/app/dummyData/lecture/getReview.json
  src/app/dummyData/main/maindto.json
  src/app/dummyData/test.설명.ts
  src/app/dummyData/timetable/getTimetable.json
Labels: feat

#9 feat(tiptap-editor): 텍스트 에디터/ 뷰 컴포넌트 구현
  package-lock.json
  package.json
  public/editor/color.webp
  src/app/(route)/layout.tsx
  src/app/(route)/test/correct/page.tsx
  src/app/(route)/test/page.tsx
  src/app/(route)/test/view/page.tsx
  src/app/(route)/test/write/page.tsx
  src/app/_components/Header/ThemeToggleButton/ThemeToggleButton.client.tsx
  src/app/_components/Header/ThemeToggleButton/ThemeToggleView.tsx
  src/app/_components/TextEditor/ColorPickerButton/ColorPickerView.tsx
  src/app/_components/TextEditor/ColorPickerButton/ColorPickerbutton.tsx
  src/app/_components/TextEditor/TextEditor.tsx
  src/app/_components/TextEditor/Toolbar/Toolbar.tsx
  src/app/_components/TextEditor/Toolbar/ToolbarAction.ts
  src/app/_components/TextViewer/TextViewer.tsx
  src/app/_components/ToggleModal/ToggleModal.tsx
  src/app/_hooks/TextEditor/EditorRule.ts
  src/app/_hooks/TextEditor/useTextEditor.ts
  src/app/_hooks/useTheme.tsx
  src/app/_styles/tiptap.css
  src/app/_types/Header/theme.type.ts
  src/app/_types/TextEditor/textEditor.type.ts
  src/app/_utils/Header/getTheme.server.ts
  src/app/api/test.ts
  src/app/api/test/getTextDto/route.ts
  src/app/dummyData/main/maindto.json
  tailwind.config.ts
Labels: feat

#12 feat(timetable): 시간표 레이아웃 구현
  src/app/(route)/timetable/page.tsx
  src/app/dummyData/timetable/getTimetable.json
  src/app/dummyData/timetable/getTimetableRecommand.json
Labels: feat, design

#20 feat(card component): 카드 컴포넌트 구현
  next.config.ts
  src/app/(route)/(main)/page.tsx
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_error.tsx
  src/app/dummyData/lecture-list/getLectureList.json
Labels: feat

#22 feat(lecture-list): 강의 목록 구현
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/_components/DayTab/groupBy.ts
  src/app/_error.tsx
  src/app/dummyData/lecture-list/getLectureList.json
  src/app/error.tsx
  src/app/layout.tsx
Labels: feat, design

#28 design(timetable): 시간표 레이아웃 변경
  src/app/(route)/timetable/page.tsx
  src/app/_components/DayTab/DayTab.tsx
Labels: design

#29 Design(mainPage): 메인 페이지 퍼블리싱
  global.d.ts
  next.config.ts
  package-lock.json
  package.json
  src/app/(route)/(main)/mainComponent/FourthSection.tsx
  src/app/(route)/(main)/mainComponent/FstSection.tsx
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/(main)/mainComponent/TrdSection.tsx
  src/app/(route)/(main)/mainComponent/_MainFooter.tsx
  src/app/(route)/(main)/mainComponent/component/OptionList.tsx
  src/app/(route)/(main)/mainComponent/component/ScrollWrapper.tsx
  src/app/(route)/(main)/mainComponent/component/SectionWrapper.tsx
  src/app/(route)/(main)/mainComponent/component/kakaoMap.tsx
  src/app/(route)/(main)/page.tsx
  src/app/(route)/_error.tsx
  src/app/(route)/layout.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/HeaderNav/HeaderNav.tsx
  src/app/_components/Script/Login.script.tsx
  src/app/_components/TextEditor/TextEditor.tsx
  src/app/_components/ToggleModal/ToggleModal.tsx
  src/app/_hooks/login/useLogin.ts
  src/app/_hooks/nav/navDto.ts
  src/app/_hooks/nav/useResize.ts
  src/app/_hooks/useTheme.ts
  src/app/_store/Main/viewportStore.ts
  src/app/_styles/globals.css
  src/app/_types/kakao.d.ts
  src/app/_utils/Header/getUserLink.ts
  src/app/api/auth/route.ts
  src/app/api/test/getLectures/route.ts
  src/app/api/test/lectures/date/route.ts
  src/app/api/test/lectures/route.ts
Labels: design

#39 Design(leature-info): 강의자 프로필 페이지 퍼블리싱
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/(main)/mainComponent/TrdSection.tsx
  src/app/(route)/(main)/mainComponent/component/kakaoMap.tsx
  src/app/(route)/instructor/[id]/page.tsx
  src/app/(route)/test/correct/page.tsx
  src/app/(route)/test/page.tsx
  src/app/(route)/test/view/page.tsx
  src/app/(route)/test/write/page.tsx
  src/app/_styles/globals.css
  src/app/_utils/Card/formatTime.ts
Labels: design

#40 fix(font-contentEdit): 폰트 굵기 적용되지 않던 문제 해결
  src/app/_styles/globals.css
Labels: fix

#41 feat(wishlist): 즐겨찾기 목록 추가
  src/app/(route)/timetable/page.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/dummyData/timetable/getWishlist.json
Labels: feat

#47 design(card component): 카드 컴포넌트 구조 및 디자인 변경
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/(main)/page.tsx
  src/app/(route)/instructor/[id]/page.tsx
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
Labels: design

#51 feat(wish): 즐겨찾기 전역 상태 관리 및 즐겨찾기 추가/삭제 기능 구현
  package-lock.json
  package.json
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/instructor/[id]/page.tsx
  src/app/(route)/lecture-list/page.tsx
  src/app/(route)/timetable/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/groupBy.ts
  src/app/_components/Wish/WishButton.tsx
  src/app/_store/LectureList/useLectureStore.ts
  src/app/dummyData/wishlist/getWishlist.json
Labels: feat

#56 feat(alarm): 알람 기능 추가
  global.d.ts
  package-lock.json
  package.json
  src/app/(route)/(main)/mainComponent/component/ScrollWrapper.tsx
  src/app/_components/Header/Alarm/Alarm.tsx
  src/app/_components/Header/Alarm/AlarmList.tsx
  src/app/_components/Header/HeaderNav/HeaderNav.tsx
  src/app/_components/Nav/navigation/HeaderNav.mobile.tsx
  src/app/_components/Nav/navigation/HeaderNav.web.tsx
  src/app/_components/ToggleModal.tsx
  src/app/_hooks/nav/useResize.ts
  src/app/_store/Header/useAlarmStore.ts
  src/app/_store/Header/useHeaderStore.ts
  src/app/_store/Main/viewportStore.ts
  src/app/_types/Header/Alarm.type.ts
  src/app/_types/assets/assets.d.ts
  src/app/_types/store.ts
  src/app/_utils/Header/getAlarmTime.ts
Labels: feat

#61 design(card): 카드 컴포넌트 배경색 추가
  src/app/_components/Card/Card.tsx
Labels: design

#64 fix(resize): 리사이즈 에러 픽스
  src/app/_components/Header/Alarm/Alarm.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/HeaderNav/HeaderNav.tsx
  src/app/_components/Nav/navigation/HeaderNav.web.tsx
Labels: bug

#66 feat(tiptap): 텍스트 에디터 이미지 기능 추가 및 API 세팅
  package-lock.json
  package.json
  src/app/(route)/write/page.tsx
  src/app/(route)/write/writeUtil.ts
  src/app/_components/TextEditor/ColorPickerButton/ColorPickerView.tsx
  src/app/_components/TextEditor/TextEditor.tsx
  src/app/_components/TextEditor/Toolbar/Toolbar.tsx
  src/app/_hooks/textEditor/useTextEditor.ts
  src/app/_types/Write/write.type.ts
Labels: feat

#71 design(lecture list): 강의 목록 디자인 수정
  src/app/(route)/layout.tsx
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/dummyData/lecture-list/getLectureList.json
Labels: design

#83 feat(ListCard): ListCard 컴포넌트 분리
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/_components/Wish/WishButton.tsx
  src/app/_types/Timetable/Lecture.type.ts
Labels: feat

#84 fix(main): 메인페이지 배경색 너비 문제 해결
  src/app/(route)/layout.tsx
  src/app/_components/LayoutWrapper.tsx
Labels: fix

#91 Feat[write-alarm]: 강의 생성 / 알림 기능 api 연동
  package-lock.json
  package.json
  src/app/(route)/write/page.tsx
  src/app/(route)/write/util/upload.ts
  src/app/_components/Header/Alarm/Alarm.tsx
  src/app/_components/Header/Alarm/AlarmList.tsx
  src/app/_components/Header/HeaderNav/HeaderNav.tsx
  src/app/_hooks/nav/useAlarm.ts
  src/app/_store/Header/useAlarmStore.ts
  src/app/_types/Header/Alarm.type.ts
  src/app/_types/Write/write.type.ts
  src/app/_utils/api/response.ts
  src/app/api/auth/admin/route.ts
  src/app/api/auth/user/refresh/route.ts
  src/app/api/auth/user/route.ts
Labels: feat

#93 feat(lecture list): 강의 목록 API 연결
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/groupBy.ts
  src/app/_store/LectureList/useLectureStore.ts
Labels: bug, feat

#94 design(mainPage): 디자인 조정 및 기능 추가
  next.config.ts
  public/main/bus.webp
  public/main/loading.gif
  public/main/mainImg.webp
  public/main/map.webp
  public/main/pin.webp
  public/main/subway.webp
  src/app/(route)/(main)/mainComponent/FourthSection.tsx
  src/app/(route)/(main)/mainComponent/FstSection.tsx
  src/app/(route)/(main)/mainComponent/SecSection.tsx
  src/app/(route)/(main)/mainComponent/TrdSection.tsx
  src/app/(route)/(main)/mainComponent/_MainFooter.tsx
  src/app/(route)/(main)/mainComponent/component/FAQItem.tsx
  src/app/(route)/(main)/mainComponent/component/ScrollWrapper.tsx
  src/app/(route)/(main)/mainComponent/component/SectionList.tsx
  src/app/(route)/(main)/mainComponent/component/SectionWrapper.tsx
  src/app/(route)/(main)/mainComponent/component/kakaoMap.tsx
  src/app/(route)/(main)/mainComponent/type/lectures.type.ts
  src/app/(route)/(main)/page.tsx
  src/app/(route)/write/page.tsx
  src/app/_components/Card/SkeletonCard.tsx
  src/app/_components/LayoutWrapper.tsx
  src/app/_components/TextViewer/TextViewer.tsx
  src/app/_hooks/nav/useAlarm.ts
  src/app/_styles/globals.css
  src/app/_types/Lectures/lectures.type.ts
  src/app/_utils/Main/getLectures.ts
  src/app/assets/Main/left.svg
  src/app/assets/Main/right.svg
Labels: feat, design

#110 design(timetable): 시간표 페이지 UI 수정
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/_components/Wish/WishButton.tsx
  src/app/assets/Timetable/Vector 3.svg
  src/app/assets/Timetable/bookmarkDouble-fill.svg
  src/app/assets/Timetable/bookmarkDouble-stroke.svg
  src/app/assets/Timetable/bookmarkSingle-fill.svg
  src/app/assets/Timetable/bookmarkSingle-stroke.svg
Labels: design

#121 feat(lecture): 강의 상세 페이지 API 연결
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
  src/app/(route)/lecture/component/publish.tsx
Labels: feat

#123 design(dark): 시간표, 강의 목록, 강의 상세페이지 다크 모드 적용
  src/app/(route)/lecture-list/page.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/_store/timetable/useTimetableStore.ts
  src/app/assets/Lecture/Download.svg
  src/app/assets/LectureList/X.svg
  src/app/assets/LectureList/arrow.svg
  src/app/assets/LectureList/filter.svg
  src/app/assets/Timetable/bookmarkDouble-fill.svg
  src/app/assets/Timetable/bookmarkDouble-stroke.svg
Labels: design, fix

#126 Design/header
  src/app/(route)/login/admin/page.tsx
  src/app/_components/Card/SkeletonCard.tsx
  src/app/_components/Header/Alarm/AlarmButton.tsx
  src/app/_components/Header/Alarm/AlarmList.tsx
  src/app/_components/Header/Alarm/AlarmWindow.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/adminTitle.tsx
  src/app/_components/Login/LoginComponent.tsx
  src/app/_components/Login/LoginModal.tsx
  src/app/_components/Nav/HeaderNav.mobile.tsx
  src/app/_components/Nav/HeaderNav.web.tsx
  src/app/_styles/globals.css
  src/app/assets/Alarm/right.svg
  src/app/assets/Header/alarm.svg
  src/app/assets/Modal/cancle.svg
Labels: design

#134 fix(reserve lecture): 강의 신청 시 로직 수정
  src/app/(route)/lecture-list/page.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/LectureReserveButton/LectureReserveButton.tsx
  src/app/_components/Popup/Popup.tsx
  src/app/_store/timetable/useTimetableStore.ts
  src/app/_utils/ReserveLecture/timeConflict.ts
  src/app/assets/Lecture/Download.svg
Labels: bug

#131 fix(lecture): 강의 상세페이지 로그인 여부 확인
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
Labels: fix

#135 design(mypage): 마이페이지 스타일 적용
  src/app/(route)/(main)/mainComponent/TrdSection.tsx
  src/app/(route)/layout.tsx
  src/app/(route)/mypage/component/dataComponents.tsx
  src/app/(route)/mypage/component/handleButton.tsx
  src/app/(route)/mypage/page.tsx
  src/app/_components/LayoutWrapper.tsx
  src/app/_components/Nav/HeaderNav.mobile.tsx
  src/app/_components/Nav/HeaderNav.web.tsx
  src/app/_hooks/auth/useAuth.ts
  src/app/_styles/globals.css
  src/app/_utils/Auth/logout.ts
  src/app/_utils/Header/toggleDarkMode.ts
  src/app/api/auth/user/route.ts
Labels: feat, design

#139 design(lecture detail): 강의 상세페이지 반응형
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
Labels: design

#141 fix(alarm): 액세스 토큰 권한이 없을 때 알림 요청하는 오류 픽스
  src/app/_hooks/nav/useAlarm.ts
Labels: fix

#142 feat(input/role): 로그인 페이지/ 마이페이지 조건 부여
  src/app/(route)/login/admin/page.tsx
  src/app/(route)/mypage/component/dataComponents.tsx
  src/app/_components/Header/Alarm/AlarmList.tsx
  src/app/_hooks/nav/useAlarm.ts
Labels: feat

#145 design(lecture-list): 강의 목록 페이지 반응형
  src/app/(route)/lecture-list/page.tsx
  src/app/_components/Card/Card.tsx
  src/app/_components/DayTab/DayTab.tsx
  src/app/assets/LectureList/X.svg
  src/app/assets/LectureList/arrow.svg
  src/app/assets/LectureList/filter.svg
Labels: design

#154 Refactor/cleanup
  src/app/(route)/admin/alarm/page.tsx
  src/app/(route)/admin/page.tsx
  src/app/(route)/instructor/[id]/page.tsx
  src/app/_components/Alarm/AlarmButton.tsx
  src/app/_components/Alarm/AlarmList.tsx
  src/app/_components/Alarm/AlarmWindow.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/ThemeToggleButton/ThemeToggleView.tsx
  src/app/_components/Header/component/AdminTitle.tsx
  src/app/_components/Header/component/ETC.tsx
  src/app/_components/Header/component/HeaderNav.tsx
  src/app/_components/Header/component/ThemeToggleButton.tsx
  src/app/_components/Login/Login.script.tsx
  src/app/_components/Nav/HeaderNav.mobile.tsx
  src/app/_components/Nav/HeaderNav.web.tsx
  src/app/_components/Popup/Popup.tsx
  src/app/_components/TextEditor/TextEditor.tsx
  src/app/_hooks/auth/useAuth.ts
  src/app/_hooks/nav/navDto.ts
  src/app/_hooks/nav/useAlarm.ts
  src/app/_hooks/nav/useNav.ts
  src/app/_store/LectureList/useLectureStore.ts
  src/app/_store/auth/useAuth.ts
  src/app/_styles/admin.css
  src/app/_types/Header/Header.type.ts
  src/app/_utils/Auth/userinfo.ts
  src/app/api/test/getLectures/route.ts
  src/app/api/test/getTextDto/route.ts
  src/app/api/test/lectures/date/route.ts
  src/app/api/test/lectures/route.ts
  src/app/dummyData/lecture-alarm/getLectureAlarm.json
  src/app/dummyData/lecture-list/getLectureList.json
  src/app/dummyData/lecture/getContents.ts
  src/app/dummyData/lecture/getLecture.json
  src/app/dummyData/lecture/getLectureContents.json
  src/app/dummyData/lecture/getQuestion.json
  src/app/dummyData/lecture/getReview.json
  src/app/dummyData/main/maindto.json
  src/app/dummyData/priority/getPriortiy.json
  src/app/dummyData/timetable/getTimeWish.json
  src/app/dummyData/timetable/getTimetable.json
  src/app/dummyData/timetable/getTimetableRecommand.json
  src/app/dummyData/wishlist/getWishlist.json
Labels: refactor

#155 design(timetable): 시간표 페이지 반응형
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/assets/Timetable/bookmarkDouble-fill.svg
  src/app/assets/Timetable/bookmarkDouble-stroke.svg
Labels: design

#159 fix(etc): 카드 컴포넌트 텍스트 크기 수정/ 다크모드 수정
  public/favicon.ico
  src/app/_components/Card/Card.tsx
  src/app/_components/Card/SkeletonCard.tsx
  src/app/_components/LectureReserveButton/LectureReserveButton.tsx
Labels: fix

#162 fix(auth): 로그인시 시간표 데이터 동기화
  src/app/_hooks/auth/useAuth.ts
Labels: fix

#166 design(lecture,list,timetable): 디자인 QA 반영
  next.config.ts
  src/app/(route)/lecture-list/component/list.tsx
  src/app/(route)/lecture/[id]/page.tsx
  src/app/(route)/lecture/component/QuestionSection.tsx
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/ListCard.tsx
  src/app/_components/TextViewer/TextViewer.tsx
  src/app/assets/Timetable/Vector 3.svg
Labels: design

#169 fix(filtering): 카테고리 필터링 후 빈 시간 라벨 제거
  src/app/(route)/lecture-list/component/list.tsx
Labels: bug

#170 Feat/timetable/querystring
  src/app/(route)/lecture-list/component/list.tsx
  src/app/(route)/lecture-list/page.tsx
  src/app/(route)/timetable/page.tsx
  src/app/(route)/timetable/timetableComponent/timetablePage.tsx
  src/app/_hooks/nav/useNav.ts
  src/app/_hooks/queryString/useQueryString.ts
Labels: feat
